#
# Build
#

set build_components {
	core init
	drivers/timer
	drivers/rtc
	server/ram_fs
	app/diff
}

source ${genode_dir}/repos/base/run/platform_drv.inc
append_platform_drv_build_components
build $build_components
create_boot_directory

#
# Generate config
#

install_config {
<config verbose="yes">
	<parent-provides>
		<service name="ROM"/>
		<service name="CAP"/>
		<service name="RM"/>
		<service name="PD"/>
		<service name="CPU"/>
		<service name="LOG"/>
		<service name="SIGNAL"/>
		<service name="IO_PORT"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="100"/>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Timer"/> </provides>
	</start>

	<start name="rtc_drv">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Rtc"/> </provides>
	</start>

	<start name="ram_fs">
		<resource name="RAM" quantum="128M"/>
		<provides> <service name="File_system"/> </provides>
		<config>
            <content>
                <rom name="test1.dat"/>
                <rom name="test1trunc.dat"/>
                <rom name="test2.dat"/>
            </content>
			<default-policy root="/" writeable="true" />
		</config>
	</start>

	<start name="diff">
		<resource name="RAM" quantum="32M"/>
		<config>
            <argv progname="diff"><arg value="test"/></argv>
			<vfs>
				<dir name="dev"> <log/> <rtc/> </dir>
                <fs/>
			</vfs>
			<libc stdout="/dev/log" stderr="/dev/log" rtc="/dev/rtc" />
		</config>
	</start>
</config>}


exec cp -fv [genode_dir]/repos/componolit/src/app/diff/test1.dat bin/
exec cp -fv [genode_dir]/repos/componolit/src/app/diff/test1trunc.dat bin/
exec cp -fv [genode_dir]/repos/componolit/src/app/diff/test2.dat bin/

#
# Boot image
#

# generic modules
set boot_modules {
	core init ld.lib.so
	timer ram_fs
    cxxthreads.lib.so
	libc.lib.so libm.lib.so posix.lib.so pthread.lib.so stdcxx.lib.so
	libbase.lib.so liblog.lib.so libargv.lib.so
	rtc_drv
	diff
    test1.dat test1trunc.dat test2.dat
}

append_platform_drv_boot_modules
build_boot_image $boot_modules

append qemu_args " -m 512 -nographic "
run_genode_until {.*child "diff" exited with exit value 0} 100
