#
# Build
#

set build_components {
	core init
	drivers/timer
	drivers/rtc
	server/vfs
	test/rm
	app/diff
	app/unzip
	app/dexdump2
	app/dexlayout
	test/libart-dexlayout
}

source ${genode_dir}/repos/base/run/platform_drv.inc
append_platform_drv_build_components
build $build_components
create_boot_directory

#
# Generate config
#

install_config {
<config verbose="no">
	<parent-provides>
		<service name="ROM"/>
		<service name="CAP"/>
		<service name="RM"/>
		<service name="PD"/>
		<service name="CPU"/>
		<service name="LOG"/>
		<service name="SIGNAL"/>
		<service name="IO_PORT"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="500"/>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Timer"/> </provides>
	</start>

	<start name="rtc_drv">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Rtc"/> </provides>
	</start>

	<start name="vfs">
		<resource name="RAM" quantum="1000M"/>
		<provides> <service name="File_system"/> </provides>
		<config>
			<vfs>
				<dir name="tmp"> <ram/> </dir>
				<dir name="android">
					<dir name="framework">
						<tar name="framework.tar"/>
					</dir>
				</dir>
			</vfs>
			<default-policy root="/" writeable="true" />
		</config>
	</start>

	<start name="apphost_config">
		<resource name="RAM" quantum="1M"/>
		<binary name="report_rom"/>
		<provides>
			<service name="Report"/>
			<service name="ROM"/>
			</provides>
		<config verbose="no">
			<policy label="apphost -> config" report="libart-dexlayout_test -> init_config"/>
			<policy label="libart-dexlayout_test -> init_state" report="apphost -> state"/>
		</config>
	</start>

	<start name="apphost" caps="1000">
		<resource name="RAM" quantum="500M"/>
			<binary name="init"/>
			<route>
				<service name="ROM" label="config"> <child name="apphost_config"/> </service>
				<service name="Report"> <child name="apphost_config"/> </service>
				<any-service> <parent/> <any-child/> </any-service>
			</route>
	</start>

	<start name="libart-dexlayout_test">
		<resource name="RAM" quantum="1000MB"/>
		<config ld_bind_now="no">
			<libexec ram="450MB" caps="500" verbose="no"/>
			<argv progname="libart-dexlayout_test">
				<arg value="--gtest_filter=-None"/>
			</argv>
			<vfs>
				<dir name="dev">
					<log/>
					<rtc/>
					<null/>
				</dir>
				<fs/>
			</vfs>
			<libc stdout="/dev/log" stderr="/dev/log" rtc="/dev/rtc" />
		</config>
		<route>
			<service name="ROM" label="init_state"> <child name="apphost_config"/> </service>
			<service name="File_system"> <child name="vfs"/> </service>
			<any-service> <parent/> <any-child/> </any-service>
		</route>
	</start>
</config>}

# Create Android framework tarball

if {![info exists ::env(ANDROID_FRAMEWORK_DIR)]} {
	puts "\nPlease set ANDROID_FRAMEWORK_DIR environment variable.\n"
	exit 0
}

puts "\nexec tar cfv bin/framework.tar -h -C $::env(ANDROID_FRAMEWORK_DIR) *.jar\n"
exec tar cfv bin/framework.tar -h -C $::env(ANDROID_FRAMEWORK_DIR) core-oj-hostdex.jar core-libart-hostdex.jar

#
# Boot image
#

# generic modules
set boot_modules {
	core init ld.lib.so
	timer vfs
	rtc_drv
	libc.lib.so libm.lib.so
	unwind.lib.so
	cxxthreads.lib.so
	posix.lib.so pthread.lib.so stdcxx.lib.so
	lwip.lib.so
	liblog.lib.so libbase.lib.so libutils.lib.so libcutils.lib.so
	libbacktrace.lib.so icu.lib.so
	libart.lib.so liblz4.lib.so libnativebridge.lib.so
	libnativehelper.lib.so libnativeloader.lib.so
	libutils.lib.so zlib.lib.so libziparchive.lib.so
	libsigchain.lib.so
	libsilence.lib.so
	libz.lib.so
	libart-dexlayout.lib.so
	libexec.lib.so
	libargv.lib.so
	librwall.lib.so
	rm
	diff
	dexdump2
	dexlayout
	unzip
	framework.tar
	libart-dexlayout_test
}

append_platform_drv_boot_modules
build_boot_image $boot_modules

append qemu_args " -m 3000 -nographic "
run_genode_until {.*child "libart-dexlayout_test" exited with exit value 0} 1000
