#
# Build
#

set build_components {
	core init
	drivers/timer
	drivers/rtc
	server/ram_fs
	test/libcutils
}

source ${genode_dir}/repos/base/run/platform_drv.inc
append_platform_drv_build_components
build $build_components
create_boot_directory

#
# Generate config
#

install_config {
<config verbose="yes">
	<parent-provides>
		<service name="ROM"/>
		<service name="CAP"/>
		<service name="RM"/>
		<service name="PD"/>
		<service name="CPU"/>
		<service name="LOG"/>
		<service name="SIGNAL"/>
		<service name="IO_PORT"/>
		<service name="IRQ"/>
		<service name="IO_MEM"/>
	</parent-provides>
	<default-route>
		<any-service> <parent/> <any-child/> </any-service>
	</default-route>
	<default caps="500"/>

	<start name="timer">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Timer"/> </provides>
	</start>

	<start name="rtc_drv">
		<resource name="RAM" quantum="1M"/>
		<provides> <service name="Rtc"/> </provides>
	</start>

	<start name="ram_fs">
		<resource name="RAM" quantum="128M"/>
		<provides> <service name="File_system"/> </provides>
		<config>
			<default-policy root="/" writeable="true" />
		</config>
	</start>

	<start name="libcutils_test">
		<resource name="RAM" quantum="128M"/>
		<config>
         <!--
		      Disabled tests:

		      TestIpv6*: IPv6 is not supported
		      Test*ReceiveTimeout: Hangs. FIXME: Otherwise file issue based on test/mfe/sock_receive_timeout
		      android_get_control_socket: No PF_UNIX socket implementation. We may not need it or replace the code.
		      TestIpv4UdpLoopback: Related to [1]
		      TestIpv4TcpLoopback: getsockopt(..SO_ERROR..) issue, FIXME: File issue based on test/mfe/getsockopt_so_error
		      str_params.put_ENOMEM: They test for hashmapPut not being influence/not influencing errno being set to ENOMEM. However, unimplemented functions in Genodes libc set ENOMEM to 'Not implemented' inbetween. This makes the final assertion fail. We ignore this test.

		      [1] https://sourceforge.net/p/genode/mailman/message/35980126/
         -->
         <argv progname="/bin/test_libcutils">
            <arg value="--gtest_filter=-SocketsTest.TestIpv6*:SocketsTest.Test*ReceiveTimeout:SocketsTest.android_get_control_socket:SocketsTest.TestIpv4*Loopback:str_parms.put_ENOMEM"/>
         </argv>
			<vfs>
				<dir name="tmp"> <fs/> </dir>
				<dir name="dev">
					<log/>
					<rtc/>
					<dir name="socket"> <fs/> </dir>
				</dir>
			</vfs>
			<libc stdout="/dev/log" stderr="/dev/log" rtc="/dev/rtc" />
		</config>
	</start>
</config>}

#
# Boot image
#

# generic modules
set boot_modules {
	core init ld.lib.so
	timer ram_fs
	libc.lib.so libm.lib.so
	vfs.lib.so
	cxxthreads.lib.so
	posix.lib.so pthread.lib.so stdcxx.lib.so
	lwip_legacy.lib.so
	libargv.lib.so
	liblog.lib.so libbase.lib.so libcutils.lib.so
	rtc_drv
	libcutils_test
}

append_platform_drv_boot_modules
build_boot_image $boot_modules

append qemu_args " -m 512 -nographic "
run_genode_until {.*child "libcutils_test" exited with exit value 0} 100
